; Drupal version
core = 7.x
api = 2

; Contrib modules
projects[apps_compatible][subdir] = contrib
projects[apps_compatible][version] = 1.0-alpha3
projects[captcha][subdir] = contrib
projects[captcha][version] = 1.0-beta2
projects[ctools][subdir] = contrib
projects[ctools][version] = 1.2
projects[features][subdir] = contrib
projects[features][version] = 1.0
projects[pathauto][subdir] = contrib
projects[pathauto][version] = 1.2
projects[strongarm][subdir] = contrib
projects[strongarm][version] = 2.0
projects[token][subdir] = contrib
projects[token][version] = 1.4
projects[views][subdir] = contrib
projects[views][version] = 3.5
