<?php

/**
 * Implementation of hook_content_features_export_render_alter()
 * Make sure that terms are not being added to the default content
 * 
 * Depends on a patch from http://drupal.org/node/1754428
 */
function panopoly_faq_question_demo_content_features_export_render_alter(&$module_name, &$node) {

  // Do not export the featured categories information since that 
  // is added as part of the installation process
  if ($node->type == 'faq') {
    unset($node->field_faq_group);
  }

  // Do not export the UUID for the images
  //if (!empty($node->field_featured_image['und'][0]['uuid'])) {
  //  unset($node->field_featured_image['und'][0]['uuid']);
  //}
}

function panopoly_faq_question_demo_init() {

  // Attach default taxonomy content to the demo content
  if (variable_get('install_task', 'done') == 'done' && !variable_get('panopoly_faq_question_demo_taxonomy', FALSE)) {

    // Determine the VID of the vocabulary
    $vid = db_select('taxonomy_vocabulary', 't')
      ->fields('t', array('vid'))
      ->condition('machine_name', 'faq_group', '=')
      ->execute()
      ->fetchField();

    // Get the terms that are in code
    module_load_include('inc', 'panopoly_faq_question_demo', 'panopoly_faq_question_demo.terms');
    $terms = panopoly_faq_question_demo_terms();

    // Load the terms and keep track of IDs
    $tids = array();
    foreach ($terms as $term) {
      $term->vid = $vid;
      taxonomy_term_save($term);
      $tids[] = $term->tid;
    }

    // Determine the nids of the demo content
    $nids = db_select('defaultcontent', 'd')
      ->fields('d', array('nid'))
      ->condition('name', db_like('panopoly-faq-question-demo') . '%', 'LIKE')
      ->execute()
      ->fetchCol();

    // Randomly assign taxonomy terms to the demo content
    foreach ($nids as $row => $nid) {
      $node = node_load($nid);
      $node->field_featured_categories['und'][] = array('tid' => $tids[array_rand($tids)]);
      $node->field_featured_categories['und'][] = array('tid' => $tids[array_rand($tids)]);
      node_save($node);
    }
 
    // Set the variable so we only do this once
    variable_set('panopoly_faq_question_demo_taxonomy', TRUE);
  }

}
