<?php
/**
 * @file
 * Code for the panopoly_faq_question feature.
 */

include_once 'panopoly_faq_question.features.inc';

function panopoly_faq_question_views_pre_render(&$view) {
  if ($view->name != 'faq') return FALSE;

  drupal_add_js(drupal_get_path('module', 'panopoly_faq_question') . '/inc/js/faq.js');
  drupal_add_css(drupal_get_path('module', 'panopoly_faq_question') . '/inc/css/faq.css');
}